version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
    - govet
    - gocritic
    - revive
    - unused
    - bodyclose
    - asciicheck
    - cyclop
    - dupl
    - ineffassign
    - unparam
    - errorlint
    - errname
    - forbidigo
    - contextcheck
    - containedctx
  disable:
    - gocyclo
    - lll
    - gosec

  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - gosec

  settings:
    gosec:
      config:
        global:
          audit: true
          show-ignored: true
        severity: "medium"
        confidence: "medium"
      exclude-rules:
        - G404
    cyclop:
      max-complexity: 20
    revive:
      severity: warning

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/sborsh1kmusora/pr-assign-service)
      no-inline-comments: false
