version: '3'

tasks:
  up-service:
    desc : "Поднять сервис"
    cmds:
      - docker compose up -d --build

  down-service:
    desc: "Остановить и удалить сервис"
    cmds:
      - docker compose down -v